### ISSUE TITLE
Existing defs are redefined instead of patched by this mod

### ISSUE THREAD

**Issue by thailyn** [Ogliss/RimWorld-Diseases-Overhauled#1]
## Background / Problem Description

Many of the Defs created by this mod are actually redefinitions of existing [vanilla] Defs. This is a very bad thing to do, stability- and mod-compatibility-wise. According to the RimWorld wiki, when a def with the same type and defName is defined, the game [only references the last one](https://rimworldwiki.com/wiki/Modding_Tutorials/Modifying_defs#Overwriting_Defs). I can confirm this appears to be in line with my experiences, as well.

While I expect any patch operations in other mods that reference that defName that are run *after* this mod will patch both versions and possibly work as expected in game, any patch operations that ran *before* this mod would essentially be deleted, as the game will never use that copy of the def.

This patching behavior can be confirmed with the [Xml Patch Helper](https://steamcommunity.com/sharedfiles/filedetails/?id=2810681278) mod. For example, after loading the game with Diseases Overhauled, search in the Xml Patch Helper's UI for `Defs/HediffDef[defName="Malnutrition"]`. This returns two results; the first is the def as defined by RimWorld Core, and the second is the def as defined by this mod (assuming a simple load order with no other mods patching these defs).

![image](https://github.com/Ogliss/RimWorld-Diseases-Overhauled/assets/292581/4d9c6983-e86e-44ec-b67e-c3d0a3808903)

## Resolution

All of the Defs in this mod that redefine existing Defs should be rewritten as patches. I'm pretty sure this was not done in the first place for simplicity, as this mod does make pretty large changes to existing hediffs and such.

I started doing something similar for a health-related mod I was working on (but I was including some additional tweaks on top), so I can instead offer PRs to do this conversion as I get to them.

## Tasks
- [ ] Rework my existing patches for inclusion in this mod.
  - [ ] Anesthetic
  - [ ] GutWorms
  - [x] Malnutrition
  - [ ] MuscleParasites
  - [ ] TraumaSavant
- [ ] Inventory this mod's remaining defs to see which others need to be updated.
- [ ] Convert those defs to patches.
